= Contributing to the Neo4j Ecosystem
:sectanchors:

At http://neo4j.com/[Neo4j], we develop our software in the open at
GitHub. This provides transparency for you, our users, and allows you to
fork the software to make your own additions and enhancements. We also
provide areas specifically for community contributions, in particular
the https://github.com/neo4j-contrib[neo4j-contrib] space.

There's an active https://community.neo4j.com/[Neo4j Online Community]
where we work directly with the community. If you're not already a
member, sign up!

We love our community and wouldn't be where we are without you. Please remember:
Many things are contributions, among them issues, code, documentation and examples.

== Tasks

=== Keep the build descriptor (`pom.xml`) sorted

[source,bash]
----
./mvnw sortpom:sort
----

=== Formatting sources / adding headers

When you add new files, you can run

[source,bash]
----
./mvnw license:format
----

to add required headers automatically.

We use https://github.com/spring-io/spring-javaformat[spring-javaformat] to format the source files.

[source,bash]
----
./mvnw spring-javaformat:apply
----

TIP: The Spring Developers write: "The source formatter does not fundamentally change your code. For example, it will not change the order of import statements. It is effectively limited to adding or removing whitespace and line feeds."
This means the following checkstyle check might still fail.

There are plugins for https://github.com/spring-io/spring-javaformat#eclipse[Eclipse] and https://github.com/spring-io/spring-javaformat#intellij-idea[IntelliJ IDEA] and the Checkstyle settings https://github.com/spring-io/spring-javaformat#checkstyle-idea-plugin[can be imported as well].
We took those "as is" and just disabled the lambda check (requiring even single parameters to have parenthesis).

Public classes do require an author tag.
Please add yourself as an `@author` to the `.java` files you added or that modified substantially (more than cosmetic changes).

== Building and compiling Neo4j-Migrations

WARNING: As of writing a loose list of how things needs to be run, not exhaustive.

=== Producing native binaries

NOTE: Native binaries for Windows, Unix and macOS are supplied since 0.3.1 at https://github.com/michael-simons/neo4j-migrations/releases[the releases page].

WARNING: The natively compiled version does not support Java-based migrations and will fail if you try to point it to any package to scan.

The Neo4j Java driver and this application supports native compilation with GraalVM so that you can create a native executable.
Read more about it https://www.graalvm.org/docs/reference-manual/native-image/[here].

After installing at least GraalVM 21.3.0 based on JDK 17, prepare your environment as follows:

[source,console,subs="verbatim,attributes"]
----
export GRAALVM_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java17-21.3.0/Contents/Home
export JAVA_HOME=$GRAALVM_HOME
----

The paths are probably different on your system.

The `neo4j-migrations-cli` module has a build profile `create-native-image` that you use to create a binary for your OS.
Run it with:

[source,console,subs="verbatim,attributes"]
----
./mvnw -Dnative clean package
----

The resulting migration tool can only be used to load Cypher script based migrations in file locations.
It won't find classes, as those are instantiated dynamically via reflection, which is not supported in full in a native image.

NOTE: You can try to use https://upx.github.io[upx] to compress your binaries. While it has some downsides on the RSS memory
      usage as explained by the folks over at https://quarkus.io/blog/upx/[the Quarkus team], the advantages of having a 2/3
      smaller binary are bigger.
      +
      If you want to enable the compression in your build, add `-DskipCompress=false` to the build.

=== Fast build

NOTE: This is useful if you want to just have an installation of a snapshot version. No tests are run, no verification is done.

[source,console,subs="verbatim,attributes"]
[[build-default-bash]]
.Fast build (only compiling and producing packages)
----
$ ./mvnw -Dfast package
----

=== Releasing (Only relevant for the current maintainers)

Releases will be created via standard Maven `release:prepare` / `release:perform` cycle.

[source,bash]
----
./mvnw release:prepare
./mvnw release:perform
----

==== Bumping minor or major versions

Use the provided script to bump the minor or major version:

[source,bash]
----
./bin/bump-version.sh 3.0
----

Version can be either a new major or minor version (such as 3, 3.0 etc.) or a fully qualified snapshot version (such as 3.0.0-SNAPSHOT).

=== Building the documentation

The documentation consists of three components:

- Javadoc (API documentation generated by Maven)
- Project info (generated by Maven)
- User documentation (generated by Antora)

You can use the following command to build both the Javadoc and the project info site using Maven:

[source,bash]
----
./mvnw compile site:site site:stage
----

To generate the user documentation, you need to https://docs.antora.org/antora/latest/install-and-run-quickstart/#install-nodejs[install Node.js].
Once you've installed Node.js, it's time to install the project dependencies using: `npm i --prefix etc/antora`.

You can now use the following command to build the user documentation:

[source,bash]
----
npm run build-local --prefix etc/antora
----

You should get the following output:

....
> neo4j-migrations-docs@1.0.0 build-local
> antora local-antora-playbook.yml

Site generation complete!
Open file:///path/to/neo4j-migrations/target/antora/index.html in a browser to view your site
....

== General considerations

=== Need to raise an issue?

Include as much information as you can in any request you make:

* Which versions of our products are you using?
* Which language (and which version of that language) are you developing
with?
* What operating system are you on?
* Are you working with a cluster or on a single machine?
* What code are you running?
* What errors are you seeing?
* What solutions have you tried already?

=== Want to contribute?

It's easier for all of us if you try to follow these steps before creating a pull request:

* Do all your work in a personal fork of the original repository
* https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request[Rebase],
don't merge (we prefer to keep our history clean)
* Create a branch (with a useful name) for your contribution
* Make sure you're familiar with the appropriate coding style (this
varies by language so ask if you're in doubt)
* Include unit tests if appropriate (obviously not necessary for
documentation changes)

NOTE: Small things that doesn't change the public API or documented behaviour and of course bug fixes usually
go in quickly. If you want to add new features with public API changes or additions or want to customize or
change a feature, please do reach out to us on one of the available channels, preferable by creating a
https://github.com/neo4j-contrib/cypher-dsl/issues/new[new issue] first in which we can discuss the proposed changes.

We can't guarantee that we'll accept pull requests and may ask you to
make some changes before they go in.
