= Neo4j Migrations
Michael Simons <michael.simons@neo4j.com>
:doctype: article
:lang: en
:listing-caption: Listing
:source-highlighter: coderay
:icons: font
:latest_version: 0.0.1

image::https://maven-badges.herokuapp.com/maven-central/eu.michael-simons.neo4j/neo4j-migrations/badge.svg[link=https://maven-badges.herokuapp.com/maven-central/eu.michael-simons.neo4j/neo4j-migrations]

[abstract]
--
This is a tool for defining Java based migrations that should be applied and recorded against a Neo4j instance.
The only dependencies are the https://github.com/neo4j/neo4j-java-driver[Neo4j Java driver] and https://github.com/classgraph/classgraph[ClassGraph], the later being used to find migrations on the classpath.

Neo4j Migrations is inspired by https://flywaydb.org[FlywayDB], which is an awesome tool for migration of relational databases.
--

== Usage

Declare the extension as Maven dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>eu.michael-simons.neo4j</groupId>
    <artifactId>neo4j-migrations</artifactId>
    <version>{latest_version}</version>
</dependency>
----

Put your migrations as Java classes into your project:

[source,java]
----
import org.neo4j.driver.Driver;

import ac.simons.neo4j.migrations.JavaBasedMigration;

public class V001__MyFirstMigration implements JavaBasedMigration {

    @Override
    public void apply(Driver driver) {
        // Steps necessary for a migration
    }
}
----

The class names must start with a `V` followed by digits followed by `__` and than some valid Java class name.

To use them create a `Migrations` instance to scan your project and apply all found migrations:

[source,java]
----
Migrations migrations = new Migrations(
    MigrationsConfig.builder().withPackagesToScan("org.company.changeset1").build(),
    GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("neo4j", "secret"))
);

migrations.apply();
----

You're migrations will be recorded as a chain of applied migrations (as nodes with the label `__Neo4jMigration`). They can use the driver any way they like.

There's no rollback yet. If any migration fails, the chain will stop, but will not rollback previous migrations.
