:numbered!:

[[appendix]]
= Appendix

== Glossary

Pending migration:: See _Resolved migration_.
Resolved migration:: A migration that has been resolved in the classpath or the filesystem which has not been yet applied.
Schema database:: A database inside a Neo4j enterprise instance or cluster that stores the schema information from Neo4j-Migrations.
Target database:: A database inside a Neo4j enterprise instance or cluster that is refactored by Neo4j-Migrations.

[[appendix_xml_schemes]]
== XML Schemes

[[appendix_xml_schemes_migration]]
=== `migration.xsd`

Before we jump into the pure joy of an https://en.wikipedia.org/wiki/XML_Schema_(W3C)[XML Schema], lets read in plain english
what our schema can do:

* A `<migration />` can have zero or exactly one `<catalog />` element.
* A `<catalog />` consists of zero or one `<constraints />` and zero or one `<indexes />` elements. In addition, it can indicate
  a `reset` attribute, replacing the current known content with the catalog currently being in definition.
* Both of them can contain zero or more of their individual elements, according to their definition.
* A `<migration />` can have zero or one `<verify />` operations and the `<verify />` operation must be the first operation.
* A `<migration />` can than have zero or more `<create />` and `<drop />` operations *or* exactly one `<apply />` operation.
  The `<apply />` operation is mutual exclusive to all operations working on single items.
* Operations that work on a single item (create and drop) are allowed to define a single item locally. This item
  won't participate in the global catalog.
* Operations that work on a single item can refer to this item by either using the attribute `item` (a free form string)
  or `ref` (an `xs:IDREF`). While the latter is useful for referring to items defined in the same migration (it will usually
  be validated by your tooling), the former is handy to refer to items defined in other migrations.

A catalog item will either have a child-element `<label />` in which case it will always refer to nodes or a mutual
exclusive child-element `<type />` in which it always refers to relationships. The `type` attribute is unrelated
to the target entity. This attribute defines the type of the element (such as unique- or existential constraints).

We do support the following processing instructions:

* `<?assert followed by a valid precondition ?>`
* `<?assume followed by a valid precondition ?>`

Look up valid preconditions xref:concepts.adoc#concepts_preconditions[here]. The full XMl schema for xref:concepts.adoc#concepts_migrations_catalog-based[catalog-based migrations] looks like this:

.migration.xsd
[source,xml,indent=0,tabsize=2]
----
include::{examplesDir}/migration.xsd[]
----

[[appendix_refactorings]]
== Refactorings

Neo4j-Migrations contains a set of ready-to-use database refactorings. These refactorings are all modelled very closely to those available in https://neo4j.com/labs/apoc/4.4/overview/apoc.refactor/[APOC] but *none* of them requires APOC to be installed in your database. The refactorings are mostly designed to work from within a <<concepts_catalog, catalog>> but they work very well on their own to. While they are part of the <<usage_core, Core API>>, they don't depend on a Migration instance. Their API is subject to the same versioning guarantees as the rest of Neo4j-Migrations. Refactorings might evolve into a their module at a later point in time.

Some refactorings require certain Neo4j versions. If you do support multiple Neo4j versions, define those refactorings as single itemed migrations and add assumptions like in the following example:

.Normalize boolean properties when running Neo4j 4.1+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<migration xmlns="https://michael-simons.github.io/neo4j-migrations">

  <?assume that version is ge 4.1 ?>

  <refactor type="normalize.asBoolean">
    <parameters>
      <parameter name="property">watched</parameter>
      <parameter name="trueValues">
        <value>y</value>
        <value>YES</value>
      </parameter>
      <parameter name="falseValues">
        <value>n</value>
        <value>NO</value>
      </parameter>
    </parameters>
  </refactor>
</migration>
----

[[applying-refactorings-programmatically]]
=== Applying refactorings programmatically
While you would normally use the declarative approach of applying refactorings from within XML / catalog based migrations, Neo4j-Migrations offers an API for it as well:


[source,java]
.Rename one type and normalize attributes to boolean in a programmatic fashion
----
try (Session session = driver.session()) {
  session.run("CREATE (m:Person {name:'Michael'}) -[:LIKES]-> (n:Person {name:'Tina', klug:'ja'})"); // <.>
}

Migrations migrations = new Migrations(MigrationsConfig.defaultConfig(), driver); // <.>

Counters counters = migrations.apply(
  Rename.type("LIKES", "MAG"), // <.>
  Normalize.asBoolean("klug", List.of("ja"), List.of("nein"))
);

try (Session session = driver.session()) {
  long cnt = session
    .run("MATCH (m:Person {name:'Michael'}) -[:MAG]-> (n:Person {name:'Tina', klug: true}) RETURN count(m)")
    .single().get(0).asLong();
  assert cnt == 1
}
----
<.> The graph that will be refactored
<.> You can create the instance as shown here or use the existing one when you already use the Spring Boot starter or the Quarkus extensions
<.> Build as many refactorings as needed, they will be applied in order. You can use the counters to check for the numbers of modifications


=== Merging nodes

`Merge.nodes(String source, List<PropertyMergePolicy> mergePolicies)` merges all the nodes, their properties and relationships onto a single node (the first in the list of matched nodes). It is important that your query uses an ordered return for this to work proper.

The `Merge` refactoring requires Neo4j 4.4+.

As catalog item:

[source,xml]
----
<refactor type="merge.nodes">
  <parameters>
    <parameter name="sourceQuery">MATCH (p:Person) RETURN p ORDER BY p.name ASC</parameter>
    <!-- Repeat as often as necessary -->
    <parameter name="mergePolicy">
      <pattern>name</pattern>
      <strategy>KEEP_LAST</strategy>
    </parameter>
    <parameter name="mergePolicy">
      <pattern>.*</pattern>
      <strategy>KEEP_FIRST</strategy>
    </parameter>
  </parameters>
</refactor>
----

=== Normalizing

Normalizing is the process to take an humongous set of properties and other Graph Items and apply a scheme to it.
The normalizing refactoring requires at least Neo4j 4.1, running it with batches requires Neo4j 4.4 or higher.

==== Normalize properties as boolean

Often times database schemes evolved over time, and you find properties with a boolean meaning and a string datatype with content such as `ja`, `HiddenB`, `yes`, `NO` or literal null. To use them proper in queries, you might want to normalize them into a real boolean value. This is done with `Normalize.asBoolean`.

`Normalize.asBoolean` takes in the name of a property and a list of values that are treated as `true` and a list of values that are treated as `false`. A property with a value that is not in any of those lists will be deleted. `null` as value is a non-existent property. However, if either lists contains literal `null`, a property will be created with the corresponding value.

By default all properties of all nodes and relationships will be normalized. To only apply this refactoring to a subset, i.e. only to nodes, you would want to use a custom query.

A Java example looks like this:

[source,java]
----
Normalize.asBoolean(
    "watched",
    List.of("y", "YES", "JA"),
	// List.of does not support literal null,
	// so we need to this the old-school
    Arrays.asList("n", "NO", null)
);
----

The same as a catalog item:

[source,xml]
----
<refactor type="normalize.asBoolean">
  <parameters>
    <parameter name="property">watched</parameter>
    <parameter name="trueValues">
      <value>y</value>
      <value>YES</value>
      <value>JA</value>
    </parameter>
    <parameter name="falseValues">
      <value>n</value>
      <value>NO</value>
      <value />
    </parameter>
    <!-- Optional custom query and batch size -->
    <!--
    <parameter name="customQuery">MATCH (n:Movie) return n</parameter>
    <parameter name="batchSize">42</parameter>
    -->
  </parameters>
</refactor>
----

=== Renaming labels, types and properties

`ac.simons.neo4j.migrations.core.refactorings.Rename` renames labels, types and properties and requires in its default form only Neo4j 3.5 to work. Custom queries for filtering target entities require Neo4j 4.1, batches Neo4j 4.4.

==== Common methods

`inBatchesOf`:: Enables or disables batching, requires Neo4j 4.4
`withCustomQuery`:: Provides a custom query matching an entity (Node or Label) for renaming. The query must return zero or more rows each containing one item. This feature requires Neo4j 4.1

==== Renaming labels

`Rename.label(String from, String to)` renames all labels on all nodes that are equal the value of `from` to the value of `to`.

As catalog item:

[source,xml]
----
<refactor type="rename.label">
  <parameters>
    <parameter name="from">Engineer</parameter>
    <parameter name="to">DevRel</parameter>
    <!-- Optional custom query -->
    <!--
    <parameter name="customQuery"><![CDATA[
      MATCH (person:Engineer)
      WHERE person.name IN ["Mark", "Jennifer", "Michael"]
      RETURN person
    ]]></parameter>
    -->
    <!-- Optional batch size (requires Neo4j 4.4+) -->
    <!--
    <parameter name="batchSize">23</parameter>
    -->
  </parameters>
</refactor>
----

==== Renaming types

`Rename.type(String from, String to)` renames all types on all relationships that are equal the value of `from` to the value of `to`.

As catalog item:

[source,xml]
----
<refactor type="rename.type">
  <parameters>
    <parameter name="from">COLLEAGUES</parameter>
    <parameter name="to">FROLLEAGUES</parameter>
    <!-- Optional custom query -->
    <!--
    <parameter name="customQuery"><![CDATA[
      MATCH (:Engineer {name: "Jim"})-[rel]->(:Engineer {name: "Alistair"})
      RETURN rel
    ]]></parameter>
    -->
    <!-- Optional batch size (requires Neo4j 4.4+) -->
    <!--
    <parameter name="batchSize">23</parameter>
    -->
  </parameters>
</refactor>
----

==== Renaming node properties

`Rename.nodeProperty(String from, String to)` renames all properties on all nodes that are equal the value of `from` to the value of `to`.

As catalog item:

[source,xml]
----
<refactor type="rename.nodeProperty">
  <parameters>
    <parameter name="from">released</parameter>
    <parameter name="to">veröffentlicht im Jahr</parameter>
    <!-- Optional custom query -->
    <!--
    <parameter name="customQuery"><![CDATA[
      MATCH (n:Movie) WHERE n.title =~ '.*Matrix.*' RETURN n
    ]]></parameter>
    -->
    <!-- Optional batch size (requires Neo4j 4.4+) -->
    <!--
    <parameter name="batchSize">23</parameter>
    -->
  </parameters>
</refactor>
----

==== Renaming type properties

`Rename.typeProperty(String from, String to)` renames all properties on all relationships that are equal the value of `from` to the value of `to`.

As catalog item:

[source,xml]
----
<refactor type="rename.relationshipProperty">
  <parameters>
    <parameter name="from">roles</parameter>
    <parameter name="to">rollen</parameter>
    <!-- Optional custom query -->
    <!--
    <parameter name="customQuery"><![CDATA[
      MATCH (n:Movie) <-[r:ACTED_IN] -() WHERE n.title =~ '.*Matrix.*' RETURN r
    ]]></parameter>
    -->
    <!-- Optional batch size (requires Neo4j 4.4+) -->
    <!--
    <parameter name="batchSize">23</parameter>
    -->
  </parameters>
</refactor>
----

=== Adding surrogate keys

You can use Neo4j-Migrations to add https://en.wikipedia.org/wiki/Surrogate_key[Surrogate Keys] aka technical keys to your Nodes and Relationships. This is especially helpful to migrate away from internal Neo4j ids, such as `id()` (Neo4j 4.4 and earlier) or `elementId()`. While these functions are useful and several Object-Graph-Mappers can use them right out of the box, they are often not what you want:

* You expose database internals as proxy for your own technical keys
* Your business now is dependent on the way the database generates them
* They might get reused (inside Neo4j), leaving you with no good guarantees for an identifier

Our build-in refactorings use `randomUUID()` to assign a https://en.wikipedia.org/wiki/Universally_unique_identifier[UUID] to a property named `id` for Nodes with a given set of labels or Relationships with a matching type for which such a property does not exist. Both the generator and the name of the property can be individually configured. Also, both type of entities can be matched with a custom query.

.Adding random UUIDs as ids to `Movie` Nodes (XML)
[source,xml]
----
<refactor type="addSurrogateKeyTo.nodes">
  <parameters>
    <parameter name="labels">
      <value>Movie</value>
    </parameter>
  </parameters>
</refactor>
----

.Adding random UUIDs as ids to `Movie` Nodes (Java)
[source,java]
----
var addSurrogateKey = AddSurrogateKey.toNodes("Movie");
----

.Adding random UUIDs as ids to `ACTED_IN` relationships (XML)
[source,xml]
----
<refactor type="addSurrogateKeyTo.relationships">
  <parameters>
    <parameter name="type">ACTED_IN</parameter>
  </parameters>
</refactor>
----

.Adding random UUIDs as ids to `ACTED_IN` relationships (Java)
[source,java]
----
var addSurrogateKey = AddSurrogateKey.toRelationships("ACTED_IN");
----

The following examples use a different target property and hard-copy the internal id into a property. Of course, you can use your own user-defined functions for generating keys. A single `%s` will be replaced with a variable holding the matched entity. The syntax for relationships is the same (as demonstrated above):

.Using a different property and generator function (XML)
[source,xml]
----
<refactor type="addSurrogateKeyTo.nodes">
  <parameters>
    <parameter name="labels">
      <value>Movie</value>
    </parameter>
    <parameter name="property">movie_pk</parameter>
    <parameter name="generatorFunction">id(%s)</parameter>
  </parameters>
</refactor>
----

.Using a different property and generator function (Java)
[source,java]
----
var addSurrogateKey = AddSurrogateKey.toNodes("Movie")
  .withProperty("movie_pk")
  .withGeneratorFunction("id(%s)");
----

=== Converting list of numbers to Vector types

NOTE: This refactoring requires a database that supports `CYPHER 25` and native vector types. As of writing all enterprise edition of Neo4j >= Neo4j 2025.10 are applicable.

Neo4j 2025.10 introduced the https://neo4j.com/docs/cypher-manual/current/values-and-types/vector/[Vector Types].
Prior to that type, `db.create.setNodeVectorProperty` and `db.create.setRelationshipVectorProperty` would create properties of type `LIST<FLOAT NOT NULL> NOT NULL`.
While these properties are still supported in current vector indexes, you might want to migrate them to `VECTOR<FLOAT NOT NULL>(n) NOT NULL` where `n` is the size of the vector.

Use `listToVectorOn.nodes` and `listToVectorOn.relationships` for that.
This refactoring allows basically for the same customization as `AddSurrogateKey` above and can be used either via an XML based catalog or programmatically.

.Change all `embedding` properties on Nodes labelled `Movie` to a `VECTOR`
[source,xml]
----
<refactor type="listToVectorOn.nodes">
    <parameters>
        <parameter name="labels">
            <value>Movie</value>
        </parameter>
    </parameters>
</refactor>
----

The refactoring assumes a property name of `embedding` by default, which of course can be configured, too:

.Change all `einbettung` properties on Nodes labelled `Movie` to a `VECTOR`
[source,xml]
----
<refactor type="listToVectorOn.nodes">
    <parameters>
        <parameter name="labels">
            <value>Movie</value>
        </parameter>
        <parameter name="property">einbettung</parameter>
    </parameters>
</refactor>
----

The following example works on relationships and uses Cypher `INTEGER32` type for the vector. Be aware that your data must fit that datatype, otherwise the DBMS will error out:

[source,xml]
----
<refactor type="listToVectorOn.relationships">
    <parameters>
        <parameter name="type">
            <value>ACTED_IN</value>
        </parameter>
        <parameter name="elementType">INTEGER32</parameter>
    </parameters>
</refactor>
----

The algorith will only work on entities that have a property with the given name and the type `LIST<FLOAT NOT NULL> NOT NULL` and not touch anything else.
Feel free to use a custom query for matching entities.

=== Migrating BTREE indexes to "future" indexes

Neo4j 4.4 introduces https://neo4j.com/docs/cypher-manual/current/indexes-for-search-performance/#indexes-future-indexes[future indexes], `RANGE` and `POINT` which replace the well known `BTREE` indexes of Neo4j 4.x. These new indexes are available from Neo4j 4.4 onwards but will not participate in any query planing in Neo4j 4.4. They exist merely for migration purposes in Neo4j 4.4: Neo4j 5.0 does not support `BTREE` indexes at all. This means a database that contains `BTREE` indexes _cannot_ be upgraded to Neo4j 5.0. Existing `BTREE` indexes need to be dropped prior to attempting the upgrade. The class `ac.simons.neo4j.migrations.core.refactorings.MigrateBTreeIndexes` has been created for this purpose. It allows creation of matching new indexes and optionally dropping the indexes that are no longer supported in Neo4j 5.0 and higher prior to upgrading the store.

As with all the other refactorings, it can be used programmatically in your own application or through Neo4j-Migrations.

==== Preparing an upgrade to Neo4j 5.0 by creating future indexes in parallel

[source,xml]
.Creating future indexes in parallel to old indexes
----
<refactor type="migrate.createFutureIndexes">
    <parameters> <!--.-->
        <parameter name="suffix">_future</parameter> <!--.-->
        <parameter name="excludes"> <!--.-->
            <value>a</value>
            <value>b</value>
        </parameter>
        <parameter name="typeMapping"> <!--.-->
            <mapping>
                <name>c</name>
                <type>POINT</type>
            </mapping>
            <mapping>
                <name>d</name>
                <type>TEXT</type>
            </mapping>
        </parameter>
    </parameters>
</refactor>
----
<.> All parameters are optional
<.> The default suffix is `_new`
<.> An `excludes` list can be used to exclude items from being processed by name. Its pendant is the `includes` list. If
the latter is not empty, only the items in the list will be processed
<.> By default, `RANGE` indexes are created. The type mapping allows to map specific old indexes to either `RANGE`, `POINT` or `TEXT`.
The type mappings are not consulted when migrating constraint-backing indexes.

When the above refactoring is applied, new indexes and constraints will be created in parallel to the old ones. The refactoring will log statements for dropping the old constraints.

==== Preparing an upgrade to Neo4j 5.0 by replacing `BTREE` indexes with future indexes

The advantage of this approach is the fact that it won't need additional manual work before doing a store upgrade. However, the store upgrade should follow closely after dropping the old indexes and creating the replacement indexes as the latter won't participate in planning at all prior to the actual upgrade to Neo4j 5.0 or higher.

[source,xml]
.Replacing `BTREE` indexes with future indexes
----
<refactor type="migrate.replaceBTreeIndexes">
    <parameters>
        <parameter name="includes">
            <value>x</value>
            <value>y</value>
        </parameter>
    </parameters>
</refactor>
----

The `suffix` parameter is not supported as it is not needed. The other parameters have the same meaning as with `migrate.createFutureIndexes`. The above example shows the `includes` parameter.

[[appendix_annotation]]
== Annotation processing

Neo4j-Migrations offers annotation processing for https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/[SDN 6] and generates <<concepts_catalog, catalogs>> containing unique constraints for all `@Node` entities using either assigned or externally generated ids (via `@Id` plus an optional external `@GeneratedValue` or without further annotation).

This is in line with recommended best practices for SDN 6:

* Use externally assigned or generated IDs instead of Neo4j internal id values (especially when making those ids available to external systems)
* Create at least indexes for them, better unique constraint to ensure that any assigned value is fit for its purpose

For more ideas and ruminations around that, please have a look at https://medium.com/neo4j/neo4j-ogm-and-spring-data-neo4j-a55a866df68c[How to choose an unique identifier for your database entities]. While that article is still from an SDN5+OGM perspective, it's core ideas still apply.

The annotation processor is available under the following coordinates:

[source,xml,subs="verbatim,attributes"]
.Annotation processor as Maven dependency
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>neo4j-migrations-annotation-processor</artifactId>
    <version>{fullVersion}</version>
</dependency>
----

It has no dependencies apart from Neo4j-Migrations itself (neither SDN6 nor Neo4j-OGM), so it is safe to use it either directly as dependency so that it will be picked up by all recent Java compilers or as dedicated processor for the compiler:

[source,xml,subs="verbatim,attributes"]
.Annotation processor configured as processor for the compiler plugin inside a Maven pom
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <annotationProcessorPaths>
            <annotationProcessorPath>
                <groupId>{groupId}</groupId>
                <artifactId>neo4j-migrations-annotation-processor</artifactId>
                <version>{fullVersion}</version>
            </annotationProcessorPath>
        </annotationProcessorPaths>
        <compilerArgs>
            <arg>-Aorg.neo4j.migrations.catalog_generator.default_catalog_name=R$\{next-migration-version}__Create_sdn_constraints.xml</arg>
            <arg>-Aorg.neo4j.migrations.catalog_generator.output_dir=my-generated-migrations</arg>
        </compilerArgs>
    </configuration>
</plugin>
----

The latter approach allows for passing additional configuration to the processor, such as the output location relativ to `target/generated-sources` and various name generators.
There is a limited API to the processor living in the `neo4j-migrations-annotation-processor-api` module, such as `ac.simons.neo4j.migrations.annotations.proc.ConstraintNameGenerator` and the `CatalogNameGenerator`.
You can provide implementations, but they must live outside the project that is being subject to compilation, as otherwise those classes can't be loaded by us.
All implementations must provide a default, publicly accessible constructor or - if they take in any nested options - a public constructor taking in exactly one argument of type `Map<String, String>`.

The scope of the generator is limited on purpose: It will generate a valid catalog declaration and by default an `<apply />` operation. The latter is safe todo because catalogs are internally bound to their migration version and elements added or changed in v2 of a catalog will be appended, no elements will be deleted from the known catalog. Optionally the generator can be configured to generate a `reset` catalog, which will start the catalog at the given version fresh.

The generator does not generate a migration in a known migrations directory nor does it use a name that will be picked up Neo4j-Migrations by default. It is your task to configure the build system in such a way that any generated migration will

- have a recognized naming schema
- a name that evaluates to a correctly ordered version number
- be part of the directories in the target that are configured to be picked by Neo4j-Migrations

Taking the above configuration of the processor one exemplary way to take this further is this:

.Adding generated migrations to the actual target dir
[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <executions>
        <execution>
            <id>copy-resources</id>
            <goals>
                <goal>copy-resources</goal>
            </goals>
            <phase>process-classes</phase>
            <configuration>
                <outputDirectory>${project.build.outputDirectory}/neo4j/migrations/</outputDirectory>
                <resources>
                    <resource>
                        <directory>${project.build.directory}/generated-sources/annotations/my-generated-migrations</directory>
                        <filtering>false</filtering>
                    </resource>
                </resources>
            </configuration>
        </execution>
    </executions>
</plugin>
----

This works in our examples but bear in mind: The migration will always be regenerated. This is fine as long as you don't change your annotated model in any capacity that results in a new or modified index (renaming attributes, labels etc.).

TIP: The generator will always use idempotent versions of indexes if available in your database. They work well with repeatable migrations.
     So one solution is to configure the generator that it generates a name like `R1_2_3__Create_domain_indexes.xml`.

One approach is to add the processor to your build and run a diff with the last "good" generated catalog and the new one. If it is different, add the new catalog under an incremented version number.

A simpler approach is using a name generator that is connected to your target dev-database using a `Migrations` instance and our api (`MigrationChain info = migrations.info(MigrationChain.ChainBuilderMode.REMOTE);`) to get the latest applied version from the `info` instance (via `.getLastAppliedVersion`) and take that and increment it and just add the catalog fresh with a new version if it has change, otherwise resuse the old name.

For the naming generation APIs are provided and for the rest, `maven-resources-plugin` and maybe `build-helper-maven-plugin` are helpful. The decision to delegate that work has been made as it is rather difficult to propose a one-size-fits-all solution within this tool for all the combinations of different setups and build-systems out there.

Options can be passed to name generators via `-Aorg.neo4j.migrations.catalog_generator.naming_options=<nestedproperties>`  with `nestedproperties` following a structure like `a=x,b=y` and so on. If you want to use that, your own name generator must provide a public constructor taking in one single `Map<String, String>` argument.

TIP: Our recommended approach is to use `javac` directly and script it's invocation in your CI/CD system
     as shown in the following paragraph!

=== Additional annotations

We offer a set of additional annotations - `@Unique`, `@Required` and `@Fulltext` that can be used standalone or together with SDN6 _or_ OGM to specify constraints on classes. Please check the JavaDoc of those annotations about their usage. The module as shown below has no dependencies, neither on Neo4j-Migrations, nor SDN6 or OGM. While it works excellent with SDN6 for specifying additional information, all annotations offer a way to define labels and relationship types.

[source,xml,subs="verbatim,attributes"]
.Annotation processor as Maven dependency
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>neo4j-migrations-annotation-catalog</artifactId>
    <version>{fullVersion}</version>
</dependency>
----

Combined with SDN6, a valid definition would look like this:

[source,java]
----
import java.util.UUID;

import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;

import ac.simons.neo4j.migrations.annotations.catalog.Required;
import ac.simons.neo4j.migrations.annotations.catalog.Unique;

@Node
public record Organization(
	@Id @GeneratedValue @Unique UUID id, // <.>
	@Required String name) {
}
----
<.> Technically, the `@Unique` annotation isn't necessary here and the processor will generate a constraint for that field out of the box, but we think it reads better that way.

=== Using Javac and our annotation processor

The annotation processor itself is made of 3 artifacts:

`neo4j-migrations-{fullVersion}.jar`:: Needed to generate the catalogs
`neo4j-migrations-annotation-processor-api-{fullVersion}.jar`:: Contains the API and built-in annotations
`neo4j-migrations-annotation-processor-{fullVersion}.jar` :: The processor itself

You need to make sure to include all of them in the processor path, otherwise you will most likely read something like `error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: ac.simons.neo4j.migrations.annotations.proc.impl.CatalogGeneratingProcessor Unable to get public no-arg constructor`, which is a bit misleading.

==== For OGM entities

You need at least `neo4j-ogm-core` as dependency for processing Neo4j-OGM entities and most likely all libraries that you are used in addition to OGM annotations in those entities. The following statement generates `V01__Create_OGM_schema.xml` in a directory `output`. It only does annotation processing:

.Generating a catalog from Neo4j-OGM entities
[source,bash,subs="verbatim,attributes"]
----
javac -proc:only \
-processorpath neo4j-migrations-{fullVersion}.jar:neo4j-migrations-annotation-processor-api-{fullVersion}.jar:neo4j-migrations-annotation-processor-{fullVersion}.jar \
-Aorg.neo4j.migrations.catalog_generator.output_dir=output \
-Aorg.neo4j.migrations.catalog_generator.default_catalog_name=V01__Create_OGM_schema.xml \
-cp neo4j-ogm-core-4.0.0.jar \
extensions/neo4j-migrations-annotation-processing/processor/src/test/java/ac/simons/neo4j/migrations/annotations/proc/ogm/*
----

==== For SDN Entities

The only difference here is that you must use SDN 6.0+ and its dependencies as a dependencies to JavaC:

.Generating a catalog from Neo4j-OGM entities
[source,bash,subs="verbatim,attributes"]
----
javac -proc:only \
-processorpath neo4j-migrations-{fullVersion}.jar:neo4j-migrations-annotation-processor-api-{fullVersion}.jar:neo4j-migrations-annotation-processor-{fullVersion}.jar \
-Aorg.neo4j.migrations.catalog_generator.output_dir=output \
-Aorg.neo4j.migrations.catalog_generator.default_catalog_name=V01__Create_SDN6_schema.xml \
-cp apiguardian-api-1.1.2.jar:spring-data-commons-2.7.2.jar:spring-data-neo4j-6.3.2.jar \
extensions/neo4j-migrations-annotation-processing/processor/src/test/java/ac/simons/neo4j/migrations/annotations/proc/sdn6/movies/*
----

==== For classes annotated with catalog annotations

No additional jars apart from the dedicated annotations are necessary

.Generating a catalog from plain annotated classes
[source,bash,subs="verbatim,attributes"]
----
javac -proc:only \
-processorpath neo4j-migrations-{fullVersion}.jar:neo4j-migrations-annotation-processor-api-{fullVersion}.jar:neo4j-migrations-annotation-processor-{fullVersion}.jar \
-Aorg.neo4j.migrations.catalog_generator.output_dir=output \
-Aorg.neo4j.migrations.catalog_generator.default_catalog_name=R01__Create_annotated_schema.xml \
-cp neo4j-migrations-annotation-catalog-{fullVersion} \
extensions/neo4j-migrations-annotation-processing/processor/src/test/java/ac/simons/neo4j/migrations/annotations/proc/catalog/valid/CoffeeBeanPure*
----

==== Neo4j 5.9+ property type constraints

The annotation processor can create property type constraints from OGM and SDN models.
These constraints will ensure that the database schema enforces the datatypes declared in the models.
To enable that feature, configure the processor with `-Aorg.neo4j.migrations.catalog_generator.generate_type_constraints=true``

[[appendix_extesions]]
== Extensions

=== CSV Support (Experimental)

include::extensions/csv.adoc[leveloffset=+2,tag=content]

=== AsciiDoctor Support (Experimental)

include::extensions/asciidoctor.adoc[leveloffset=+2,tag=content]

=== Markdown Support (Experimental)

include::extensions/markdown.adoc[leveloffset=+2,tag=content]
