[[download]]
= Download

[[download_cli]]
== CLI

=== SDKMAN!

Neo4j-Migrations is on https://sdkman.io/sdks#neo4jmigrations[SDKMAN!] and can be installed via

[source,console]
----
sdk install neo4jmigrations
----

on Windows, Linux and macOS x86_64.
Arm binaries are not yet available.

[[download_cli_brew]]
=== For homebrew users on macOS

[source,console]
----
brew install michael-simons/homebrew-neo4j-migrations/neo4j-migrations
----

Autocompletion is automatically installed and available for bash and zsh when you configured Homebrew https://docs.brew.sh/Shell-Completion[accordingly].

=== Linux

As download from our {url-gh-releases}[release page]:

[source,console,subs="verbatim,attributes"]
----
curl -LO {url-gh-releases}/download/{fullVersion}/neo4j-migrations-{fullVersion}-linux-x86_64.zip
----

=== Windows

As download from our {url-gh-releases}[release page]:

[source,console,subs="verbatim,attributes"]
----
curl -LO {url-gh-releases}/download/{fullVersion}/neo4j-migrations-{fullVersion}-windows-x86_64.zip
----

=== Architecture independent

In addition to the above native binaries we still offer a JVM, architecture independent version of Neo4j-Migrations-CLI.
Only the JVM version does support custom, Java-based migrations as shown via the argument `--package`, the natively compiled versions do not.
Get this version here:

[source,console,subs="verbatim,attributes"]
----
curl -LO {url-gh-releases}/download/{fullVersion}/neo4j-migrations-{fullVersion}.zip
----

TIP: The architecture independent version can be used via Neo4js https://www.jbang.dev[JBang] catalog:
     +
     With JBang installed, run `jbang neo4j-migrations@neo4j --help` for printing our usage information.
     +
     The catalog offers a couple of other scripts as well, check them out with `jbang catalog list neo4j`.
     +
     We cannot update the catalog automatically, so sometimes it may is behind a version or two. Also, once you used the runner, JBang might never update it's local cache anynore. Use `jbang cache clear --all` to force that.

[[download_core]]
== Core API

The easiest way to get the Core API is to use a build- and dependency-management tool like Maven or Gradle.
Here are the coordinates:

[source,xml,subs="verbatim,attributes"]
.Core API as Maven dependency
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>{artifactIdCore}</artifactId>
    <version>{fullVersion}</version>
</dependency>
----

Or in case you fancy Gradle:

[source,groovy,subs="verbatim,attributes"]
.Core API as Gradle dependency
----
dependencies {
    implementation '{groupId}:{artifactIdCore}:{fullVersion}'
}
----

[[download_springboot]]
== Spring-Boot-Starter

Use your dependency management to include the https://start.spring.io[Spring-Boot]-Starter.
The starter automatically triggers the dependency to the Neo4j-Java-Driver, which than can be configured via properties in the `spring.neo4j.*` namespace.
This starter here has a custom namespace, please refer to xref:usage.adoc#usage_spring-boot-starter[for more information].

[source,xml,subs="verbatim,attributes"]
.Neo4j-Migrations-Spring-Boot-Starter as Maven dependency
----
<dependencies>
    <dependency>
        <groupId>{groupId}</groupId>
        <artifactId>{artifactIdSpringBoot}</artifactId>
        <version>{fullVersion}</version>
    </dependency>
</dependencies>
----

Or in case you fancy Gradle:

[source,gradle,subs="verbatim,attributes"]
.Neo4j-Migrations-Spring-Boot-Starter as Gradle dependency
----
dependencies {
    implementation '{groupId}:{artifactIdSpringBoot}:{fullVersion}'
}
----

[[download_quarkus]]
== Quarkus

Use your dependency management to include the https://quarkus.io[Quarkus] extension.
This extension automatically triggers the dependency to the Neo4j extension containing the Neo4j-Java-Driver.
The latter can be configured via properties in the `++quarkus.neo4j.*++` namespace.
The namespace for this extension is also `++org.neo4j.migrations.*++`.

[source,xml,subs="verbatim,attributes"]
.Neo4j-Migrations for Quarkus as Maven dependency
----
<dependencies>
    <dependency>
        <groupId>{groupId}</groupId>
        <artifactId>{artifactIdQuarkus}</artifactId>
        <version>{fullVersion}</version>
    </dependency>
</dependencies>
----

== Maven-Plugin

Include the Maven-Plugin like this in your build and configure it according to the xref:usage.adoc#usage_maven-plugin[usage section]:

[source,xml,subs="verbatim,attributes"]
----
<plugins>
    <plugin>
        <groupId>{groupId}</groupId>
        <artifactId>{artifactIdMavenPlugin}</artifactId>
        <version>{fullVersion}</version>
        <configuration>
            <user>neo4j</user>
            <password>secret</password>
            <address>bolt://localhost:$\{it-database-port}</address>
            <verbose>true</verbose>
        </configuration>
        <executions>
            <execution>
                <id>migrate</id>
                <goals>
                    <goal>migrate</goal>
                </goals>
            </execution>
            <execution>
                <id>default-validate</id>
                <goals>
                    <goal>validate</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
</plugins>
----
