CREATE CONSTRAINT IF NOT EXISTS FOR (n:Book) REQUIRE n.title IS UNIQUE;
CREATE CONSTRAINT constraint_name1 FOR (n:Person) REQUIRE (n.firstname, n.surname) IS NODE KEY;
CREATE CONSTRAINT constraint_name1 IF NOT EXISTS FOR (n:Person) REQUIRE (n.firstname, n.surname) IS NODE KEY;
CREATE CONSTRAINT constraint_name2 FOR (n:Book) REQUIRE (n.a, n.b) IS UNIQUE;
CREATE CONSTRAINT constraint_name3 FOR (n:Book) REQUIRE n.isbn IS NOT NULL;
CREATE CONSTRAINT constraint_name3 IF NOT EXISTS FOR (n:Book) REQUIRE n.isbn IS NOT NULL;
CREATE CONSTRAINT constraint_name4 FOR ()-[r:LIKED]-() REQUIRE r.day IS NOT NULL;
CREATE CONSTRAINT constraint_name4 IF NOT EXISTS FOR ()-[r:LIKED]-() REQUIRE r.day IS NOT NULL;
CREATE CONSTRAINT constraint_name5 FOR (n:Book) REQUIRE n.isbn IS UNIQUE;
CREATE CONSTRAINT constraint_name5 IF NOT EXISTS FOR (n:Book) REQUIRE n.isbn IS UNIQUE;
