[[download]]
= Download

[[download_cli]]
== CLI

[[download_cli_brew]]
=== For homebrew users on macOS

[source,console]
----
brew install michael-simons/homebrew-neo4j-migrations/neo4j-migrations
----

Autocompletion is automatically installed and available for bash and zsh when you configured Homebrew https://docs.brew.sh/Shell-Completion[accordingly].

=== Linux

As download from our https://github.com/michael-simons/neo4j-migrations/releases[release page]:

[source,console,subs="verbatim,attributes"]
----
curl -LO https://github.com/michael-simons/neo4j-migrations/releases/download/{latest_version}/neo4j-migrations-{latest_version}-linux-x86_64.zip
----

=== Windows

As download from our https://github.com/michael-simons/neo4j-migrations/releases[release page]:

[source,console,subs="verbatim,attributes"]
----
curl -LO https://github.com/michael-simons/neo4j-migrations/releases/download/{latest_version}/neo4j-migrations-{latest_version}-windows-x86_64.zip
----

=== Architecture independent

In addition to the above native binaries we still offer a JVM, architecture independent version of Neo4j-Migrations-CLI.
Only the JVM version does support custom, Java-based migrations as shown via the argument `--package`, the natively compiled versions do not.
Get this version here:

[source,console,subs="verbatim,attributes"]
----
curl -LO https://github.com/michael-simons/neo4j-migrations/releases/download/{latest_version}/neo4j-migrations-{latest_version}.zip
----

[[download_core]]
== Core API

The easiest way to get the Core API is to use a build- and dependency-management tool like Maven or Gradle.
Here are the coordinates:

[source,xml,subs="verbatim,attributes"]
.Core API as Maven dependency
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>{artifactIdCore}</artifactId>
    <version>{latest_version}</version>
</dependency>
----

Or in case you fancy Gradle:

[source,xml,subs="verbatim,attributes"]
.Core API as Gradle dependency
----
dependencies {
    implementation '{groupId}:{artifactIdCore}:{latest_version}'
}
----

[[download_springboot]]
== Spring-Boot-Starter

Use your dependency management to include the https://start.spring.io[Spring-Boot]-Starter.
The starter automatically triggers the dependency to the Neo4j-Java-Driver, which than can be configured via properties in the `spring.neo4j.*` namespace.
This starter here has a custom namespace, please refer to <<usage_spring-boot-starter>> for more information.

[source,xml,subs="verbatim,attributes"]
.Neo4j-Migrations-Spring-Boot-Starter as Maven dependency
----
<dependencies>
    <dependency>
        <groupId>{groupId}</groupId>
        <artifactId>{artifactIdSpringBoot}</artifactId>
        <version>{latest_version}</version>
    </dependency>
</dependencies>
----

Or in case you fancy Gradle:

[source,xml,subs="verbatim,attributes"]
.Neo4j-Migrations-Spring-Boot-Starter as Gradle dependency
----
dependencies {
    implementation '{groupId}:{artifactIdSpringBoot}:{latest_version}'
}
----

[[download_quarkus]]
== Quarkus

Use your dependency management to include the https://quarkus.io[Quarkus] module.
The module automatically triggers the dependency to the Neo4j-Java-Driver, which than can be configured via properties in the `++quarkus.neo4j.*++` namespace.
The namespace for this Quarkus module is `++quarkus.neo4j.migrations.*++`.

[source,xml,subs="verbatim,attributes"]
.Neo4j-Migrations for Quarkus as Maven dependency
----
<dependencies>
    <dependency>
        <groupId>{groupId}</groupId>
        <artifactId>{artifactIdQuarkus}</artifactId>
        <version>{latest_version}</version>
    </dependency>
</dependencies>
----

== Maven-Plugin

Include the Maven-Plugin like this in your build and configure it according to <<usage_maven-plugin>>:

[source,xml,subs="verbatim,attributes"]
----
<plugins>
    <plugin>
        <groupId>{groupId}</groupId>
        <artifactId>{artifactIdMavenPlugin}</artifactId>
        <version>{latest_version}</version>
        <configuration>
            <user>neo4j</user>
            <password>secret</password>
            <address>bolt://localhost:${it-database-port}</address>
            <verbose>true</verbose>
        </configuration>
        <executions>
            <execution>
                <id>migrate</id>
                <goals>
                    <goal>migrate</goal>
                </goals>
            </execution>
            <execution>
                <id>default-validate</id>
                <goals>
                    <goal>validate</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
</plugins>
----
